language: python

python:
  - '3.5'

script:
  - if [[ $TRAVIS_PYTHON_VERSION != 2.7 ]]; then /bin/bash ./tools/check_code_style.sh; fi

notifications:
  email:
    on_success: change
    on_failure: always
